# Starbucks reviews ☕️☕️

1. Import pandas

In [1]:
import pandas as pd

2. Read the data from starbucks_reviews.csv

In [9]:
dataset = pd.read_csv("starbucks_reviews.csv")
dataset.head()

,name,location,Rating,Review,date
0,Helen,"Wichita Falls, TX",5.0,Amber and LaDonna at the Starbucks on Southwes...,"September 13, 2023"
1,Courtney,"Apopka, FL",5.0,** at the Starbucks by the fire station on 436...,"July 16, 2023"
2,Daynelle,"Cranberry Twp, PA",5.0,I just wanted to go out of my way to recognize...,"July 5, 2023"
3,Taylor,"Seattle, WA",5.0,Me and my friend were at Starbucks and my card...,"May 26, 2023"
4,Tenessa,"Gresham, OR",5.0,I’m on this kick of drinking 5 cups of warm wa...,"January 22, 2023"

3. How many columns/lines are in the dataset?

In [10]:
print(dataset.shape)

(850, 5)

4. Convert the column "date" into datetime type.

💡 You'll have to specify the format with python's [strptime syntax](https://docs.python.org/3/library/datetime.html#strftime-strptime-behavior)

In [13]:
dataset['date'] = pd.to_datetime(dataset['date'])
dataset['year'] = dataset['date'].dt.year
dataset['month'] = dataset['date'].dt.month
dataset['weekday'] = dataset['date'].dt.dayofweek
dataset.head()

,name,location,Rating,Review,date,year,month,weekday
0,Helen,"Wichita Falls, TX",5.0,Amber and LaDonna at the Starbucks on Southwes...,2023-09-13,2023,9,2
1,Courtney,"Apopka, FL",5.0,** at the Starbucks by the fire station on 436...,2023-07-16,2023,7,6
2,Daynelle,"Cranberry Twp, PA",5.0,I just wanted to go out of my way to recognize...,2023-07-05,2023,7,2
3,Taylor,"Seattle, WA",5.0,Me and my friend were at Starbucks and my card...,2023-05-26,2023,5,4
4,Tenessa,"Gresham, OR",5.0,I’m on this kick of drinking 5 cups of warm wa...,2023-01-22,2023,1,6

5. Extract some features from the "date" column:
* year
* month
* day of week

,name,location,Rating,Review,date,year,month,weekday
0,Helen,"Wichita Falls, TX",5.0,Amber and LaDonna at the Starbucks on Southwes...,2023-09-13,2023,9,2
1,Courtney,"Apopka, FL",5.0,** at the Starbucks by the fire station on 436...,2023-07-16,2023,7,6
2,Daynelle,"Cranberry Twp, PA",5.0,I just wanted to go out of my way to recognize...,2023-07-05,2023,7,2
3,Taylor,"Seattle, WA",5.0,Me and my friend were at Starbucks and my card...,2023-05-26,2023,5,4
4,Tenessa,"Gresham, OR",5.0,I’m on this kick of drinking 5 cups of warm wa...,2023-01-22,2023,1,6

6. Convert the "Review" column into lowercase

In [15]:
dataset['Review'] = dataset['Review'].str.lower()
dataset.head()

,name,location,Rating,Review,date,year,month,weekday
0,Helen,"Wichita Falls, TX",5.0,amber and ladonna at the starbucks on southwes...,2023-09-13,2023,9,2
1,Courtney,"Apopka, FL",5.0,** at the starbucks by the fire station on 436...,2023-07-16,2023,7,6
2,Daynelle,"Cranberry Twp, PA",5.0,i just wanted to go out of my way to recognize...,2023-07-05,2023,7,2
3,Taylor,"Seattle, WA",5.0,me and my friend were at starbucks and my card...,2023-05-26,2023,5,4
4,Tenessa,"Gresham, OR",5.0,i’m on this kick of drinking 5 cups of warm wa...,2023-01-22,2023,1,6

7. Extract features from the "Review" column:
* Count the occurrences of the word "starbucks"
* Count the total number of words in each review

In [18]:
#count the occurences of "starbucks"
dataset["count_starbucks"]=dataset["Review"].str.count("starbucks")

#count words
dataset["wordcount"] = dataset["Review"].str.split().apply(lambda x: len(x))

dataset.head()

,name,location,Rating,Review,date,year,month,weekday,count_starbucks,wordcount
0,Helen,"Wichita Falls, TX",5.0,amber and ladonna at the starbucks on southwes...,2023-09-13,2023,9,2,1,60
1,Courtney,"Apopka, FL",5.0,** at the starbucks by the fire station on 436...,2023-07-16,2023,7,6,2,105
2,Daynelle,"Cranberry Twp, PA",5.0,i just wanted to go out of my way to recognize...,2023-07-05,2023,7,2,1,72
3,Taylor,"Seattle, WA",5.0,me and my friend were at starbucks and my card...,2023-05-26,2023,5,4,1,86
4,Tenessa,"Gresham, OR",5.0,i’m on this kick of drinking 5 cups of warm wa...,2023-01-22,2023,1,6,3,74

8. Use pandas' `.describe()` method to get some basic statistics about the dataset and answer the questions below:
* Are the reviews rather good or bad?
* Are the reviews recent or old?
* Are the reviews rather long or short?
* Do people mention a lot the word "starbuck" ?

In [21]:
dataset.describe(include = "all")

,name,location,Rating,Review,date,year,month,weekday,count_starbucks,wordcount
count,850,850,705.000000,850,850,850.000000,850.000000,850.000000,850.000000,850.000000
unique,604,633,NaN,814,NaN,NaN,NaN,NaN,NaN,NaN
top,Linda,"New York, NY",NaN,no review text,NaN,NaN,NaN,NaN,NaN,NaN
freq,13,14,NaN,37,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,NaN,1.870922,NaN,2016-02-17 12:38:57.882352896,2015.600000,6.897647,2.955294,1.241176,88.243529
min,NaN,NaN,1.000000,NaN,2000-07-19 00:00:00,2000.000000,1.000000,0.000000,0.000000,3.000000
25%,NaN,NaN,1.000000,NaN,2012-09-26 18:00:00,2012.000000,4.000000,1.000000,0.000000,50.000000
50%,NaN,NaN,1.000000,NaN,2016-05-31 00:00:00,2016.000000,7.000000,3.000000,1.000000,85.000000
75%,NaN,NaN,2.000000,NaN,2019-01-06 06:00:00,2019.000000,10.000000,5.000000,2.000000,123.000000
max,NaN,NaN,5.000000,NaN,2023-09-14 00:00:00,2023.000000,12.000000,6.000000,9.000000,219.000000
std,NaN,NaN,1.397672,NaN,NaN,4.258436,3.400633,1.961437,1.248584,46.339488